server:
  port: 9090
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
      settings:
        web-allow-others: true
  allowed:
    resources: /h2-console/**
  sql:
    init:
      mode: always
  security:
    basic:
      enabled: true
      authorize-mode: NONE
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect
tenants:
  datasource:
    auth:
      url: jdbc:h2:mem:auth
      username: test
      password: test
      driver-class-name: org.h2.Driver
application:
  security:
    jwt:
      secret-key: 404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970
      expiration: 86400000 # a day
      refresh-token:
        expiration: 604800000 # 7 days

logging:
  level:
    root: INFO
    org:
      springframework.jdbc.datasource.init: TRACE
      zalando:
        logbook: TRACE